name: Package Release Test Anaconda.org

on:
  workflow_dispatch:

jobs:
  publish-to-anaconda:
    runs-on: ubuntu-latest

    environment:
      name: anaconda
      url: https://anaconda.org/switcherapi/switcher-client

    steps:
    - uses: actions/checkout@v6

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        channels: conda-forge
        channel-priority: strict
        conda-remove-defaults: true

    - name: Install build tools
      shell: bash -el {0}
      run: conda install -y conda-build anaconda-client

    - name: Get package version
      shell: bash -el {0}
      run: |
        PKG_VER=$(grep '__version__' switcher_client/version.py | cut -d'"' -f2)
        echo "PKG_VERSION=$PKG_VER" >> $GITHUB_ENV
        printf "pkg_version:\n  - $PKG_VER\n" > conda.recipe/conda_build_config.yaml

    - name: Build conda package
      shell: bash -el {0}
      run: conda build --no-test conda.recipe/ --output-folder dist/ -c conda-forge

    - name: Publish distribution to Anaconda.org
      shell: bash -el {0}
      run: |
        anaconda \
          --token ${{ secrets.ANACONDA_TOKEN }} \
          upload \
          --user switcherapi \
          --label test \
          $(find dist/ -name "*.tar.bz2" -o -name "*.conda")
