name: Staging CI
run-name: Staging - Python ${{ github.event.inputs.python }} / ${{ github.event.inputs.os }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      python:
        description: 'Python version'
        required: true
        default: '3.13'
      os:
        description: 'Operating System (ubuntu-20.04, ubuntu-latest, windows-latest)'
        required: true
        default: 'ubuntu-latest'

jobs:
  build-test:
    name: Build & Test - Python ${{ github.event.inputs.python }} on ${{ github.event.inputs.os }}
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python }}

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      
      - name: Test
        run: pipenv run pytest -v